### ISSUE TITLE
google-chrome-stable : Depends: libu2f-udev but it is not installable

### ISSUE THREAD

**Issue by andreeapan** [webdriverio/selenium-standalone#751]
I’ve updated the Chrome version from 108.0.5359.98-1 to 109.0.5414.74-1 in my Docker file.

WebdriverIO Version
7.16.14

Node.js Version
19.3.0

These are my commands in Dockerfile:

FROM webdriverio/selenium-standalone:latest
ARG CHROME_VERSION="109.0.5414.74-1”
RUN wget --no-verbose -O /tmp/chrome.deb [https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb](https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_$%7BCHROME_VERSION%7D_amd64.deb)
&& apt install -y -f /tmp/chrome.deb
&& rm /tmp/chrome.deb

This is the error I get in Jenkins when I try to build the docker image:
google-chrome-stable : Depends: libu2f-udev but it is not installable

And if I try to install the library separately, it gets: "Package 'libu2f-udev' has no installation candidate”

Upon further investigation, I’ve noticed that the docker image for wdio uses a base image in ubuntu 18 but with the apt-get repositories put in the source.list are specific to ubuntu 16.

**Comment by vanceaoana** [comment]
Replace xenial dependencies with:
```
RUN  echo "deb http://archive.ubuntu.com/ubuntu bionic main universe\n" > /etc/apt/sources.list \
  && echo "deb http://archive.ubuntu.com/ubuntu bionic-updates main universe\n" >> /etc/apt/sources.list \
  && echo "deb http://security.ubuntu.com/ubuntu bionic-security main universe\n" >> /etc/apt/sources.list
```

**Comment by spaudel1** [comment]
I am having similar issue

Here is my yml
```
image: webdriverio/selenium-standalone

clone:
  depth: 1
pipelines:
  branches: 
    master:
      - parallel:
          - step:
              name: Build and Run UI Tests
              caches:
                - node
              script:
                - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
                - sudo apt-get update 
                - sudo apt-get -f install google-chrome-stable
                - npm test

```

Here is the error I get:
```

sudo apt-get -f install google-chrome-stable

Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 google-chrome-stable : Depends: libu2f-udev but it is not installable
E: Unable to correct problems, you have held broken packages.
```
Any workaround?
